[package]
name = "router_derive"
description = "Utility macros for the `router` crate"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
license.workspace = true

[lib]
proc-macro = true
doctest = false

[dependencies]
darling = "0.14.4"
indexmap = "2.0.0"
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = { version = "1.0.109", features = ["full", "extra-traits"] } # the full feature does not seem to encompass all the features
